# Generated by Django 3.2.23 on 2024-06-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('AssessmentID', models.AutoField(primary_key=True, serialize=False)),
                ('AssessmentName', models.CharField(max_length=100)),
                ('MaxScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseDescription', models.TextField(blank=True)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('InstructorID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('DateOfBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('GradeID', models.AutoField(primary_key=True, serialize=False)),
                ('Score', models.IntegerField()),
                ('Assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.assessment')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('EnrollmentID', models.AutoField(primary_key=True, serialize=False)),
                ('EnrollmentDate', models.DateField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('CourseInstructorID', models.AutoField(primary_key=True, serialize=False)),
                ('AssignmentDate', models.DateField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.instructor')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
