# Generated by Django 3.2.23 on 2024-06-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='CourseID',
            new_name='CourseiD',
        ),
    ]
