# Generated by Django 3.2.23 on 2024-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20240620_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
